// ═══════════════════════════════════════════
// 1000 Razones por las que Te Amo, Paul
// ═══════════════════════════════════════════

(function () {
    'use strict';

    const razones = [
        "Por tu sonrisa que ilumina mi mundo",
        "Por cómo me haces reír cuando más lo necesito",
        "Por tu mirada que me hace sentir en casa",
        "Por tu voz, que es mi melodía favorita",
        "Por la forma en que me abrazas",
        "Por ser mi mejor amigo",
        "Por tu paciencia infinita",
        "Por cómo me haces sentir especial cada día",
        "Porque contigo el tiempo se detiene",
        "Por las mariposas que siento cuando te veo",
        "Por tu risa contagiosa",
        "Por la forma en que dices mi nombre",
        "Porque me haces querer ser mejor persona",
        "Por los momentos de silencio cómodo a tu lado",
        "Por tu bondad con todos los que te rodean",
        "Por cómo cuidas de mí",
        "Porque eres mi primer pensamiento al despertar",
        "Y mi último pensamiento antes de dormir",
        "Por tu forma única de ver el mundo",
        "Por cómo me miras cuando crees que no te veo",
        "Por tu corazón enorme",
        "Porque me enseñaste lo que es el amor verdadero",
        "Por cada mensaje de buenos días",
        "Por cada buenas noches con un beso",
        "Por tu valentía ante la vida",
        "Por cómo me defiendes siempre",
        "Porque eres mi lugar seguro",
        "Por tu ternura en los momentos difíciles",
        "Por las carcajadas que compartimos",
        "Porque contigo todo es una aventura",
        "Por tu inteligencia que me inspira",
        "Por cómo me escuchas de verdad",
        "Porque nunca me juzgas",
        "Por tu lealtad inquebrantable",
        "Porque eres mi compañero perfecto",
        "Por las pequeñas sorpresas que me das",
        "Por tu creatividad que me asombra",
        "Porque me aceptas tal como soy",
        "Por cómo caminas a mi lado",
        "Por tu mano que busca la mía",
        "Porque me haces creer en el para siempre",
        "Por tu fortaleza en los momentos duros",
        "Porque eres mi calma en la tormenta",
        "Por tu honestidad conmigo",
        "Porque me haces sentir protegida",
        "Por cada plan que hacemos juntos",
        "Porque sueño con un futuro contigo",
        "Por cómo me abrazas cuando lloro",
        "Porque me motivas a seguir adelante",
        "Por las noches viendo películas juntos",
        "Porque eres el amor de mi vida",
        "Por tu sentido del humor único",
        "Porque me haces sentir la más bonita",
        "Por la pasión con la que haces todo",
        "Porque me enseñas cosas nuevas",
        "Por tu determinación admirable",
        "Porque siempre estás ahí para mí",
        "Por la forma en que me besas",
        "Porque transformas lo ordinario en extraordinario",
        "Por cada vez que me dices 'te amo'",
        "Porque me haces sentir invencible",
        "Por tu generosidad sin límites",
        "Porque cada día te amo más que ayer",
        "Por cómo me tomás de la mano",
        "Porque eres mi todo",
        "Por la conexión inexplicable entre nosotros",
        "Porque me haces querer madrugar contigo",
        "Por tus ojos que hablan sin palabras",
        "Porque me rescatas de mis días grises",
        "Por tu capacidad de hacerme feliz",
        "Porque me das paz",
        "Por cómo bailas conmigo en la cocina",
        "Porque eres mi confidente",
        "Por tu dulzura al despertar",
        "Porque me apoyas en mis sueños",
        "Por cada promesa que me has cumplido",
        "Porque me haces creer en los cuentos de hadas",
        "Por tu aroma que me envuelve",
        "Porque eres mi persona favorita del universo",
        "Por las conversaciones hasta la madrugada",
        "Porque me haces sentir mariposas después de tanto tiempo",
        "Por cómo me cuidas cuando estoy enferma",
        "Porque me amas con mis defectos",
        "Por tu nobleza de espíritu",
        "Porque me inspiras cada día",
        "Por la seguridad que me das",
        "Porque me haces creer en mí misma",
        "Por cada beso en la frente",
        "Porque eres la mejor parte de mi día",
        "Por tu risa cuando te cuento algo tonto",
        "Porque me escogiste a mí",
        "Por cada mañana a tu lado",
        "Porque eres mi hogar",
        "Por tu espíritu libre",
        "Porque me complementas perfectamente",
        "Por las locuras que hacemos juntos",
        "Porque me haces sentir viva",
        "Por tu presencia que me tranquiliza",
        "Porque cambiaste mi vida para siempre",
        // 101–200
        "Porque me enseñaste a amar sin miedo",
        "Por las tardes de lluvia abrazados",
        "Por tu forma de resolver los problemas",
        "Porque me haces sentir que puedo con todo",
        "Por cada caricia que me das",
        "Porque eres mi razón de sonreír",
        "Por tu empatía con los demás",
        "Porque me das fuerzas cuando me faltan",
        "Por las canciones que me dedicas",
        "Porque me miras como si fuera la única",
        "Por tu forma de cocinar para mí",
        "Porque me haces olvidar mis preocupaciones",
        "Por cada foto juntos que guardamos",
        "Porque eres mi cómplice de vida",
        "Por tu capacidad de sorprenderme",
        "Porque me haces querer ser valiente",
        "Por las caminatas de la mano",
        "Porque me entiendes sin necesidad de hablar",
        "Por tu forma de pedir perdón",
        "Porque eres mi sol en los días nublados",
        "Por cómo me presentas con orgullo",
        "Porque me haces sentir amada",
        "Por tu fe en nosotros",
        "Porque siempre me animas a intentarlo",
        "Por los viajes que planeamos juntos",
        "Porque me das esperanza",
        "Por tu corazón de oro",
        "Porque celebras mis logros como tuyos",
        "Por cada momento mágico a tu lado",
        "Porque me enseñaste que el amor es paciente",
        "Por tu forma de mirarme a los ojos",
        "Porque compartes conmigo tus sueños",
        "Por las risas entre sábanas",
        "Porque me haces sentir la más afortunada",
        "Por tu fuerza interior",
        "Porque me das mil razones para quedarme",
        "Por cómo me abrazas por detrás",
        "Porque eres mi inspiración diaria",
        "Por cada te quiero susurrado",
        "Porque me haces querer construir un hogar contigo",
        "Por tu sonrisa cuando me ves llegar",
        "Porque me haces sentir segura en tus brazos",
        "Por tu manera de hacerme sentir única",
        "Porque eres el dueño de mi corazón",
        "Por cada vez que me esperas despierto",
        "Porque me das los mejores abrazos del mundo",
        "Por tu humor en los peores momentos",
        "Porque me acompañas en mis batallas",
        "Por la ternura en tu voz",
        "Porque me amas tal como soy, sin filtros",
        // 151–200
        "Por tu capacidad de perdonar",
        "Porque me haces creer que todo va a estar bien",
        "Por cada desayuno juntos",
        "Porque eres mi ancla en el caos",
        "Por cómo juegas conmigo como niños",
        "Porque me haces soñar despierta",
        "Por tu pasión por la vida",
        "Porque eres el mejor compañero de equipo",
        "Por las puestas de sol juntos",
        "Porque me demuestras que el amor existe",
        "Por tu forma de acariciar mi pelo",
        "Porque me haces sentir que vuelo",
        "Por cada secreto que compartimos",
        "Porque me das la confianza para ser yo misma",
        "Por tu energía contagiosa",
        "Porque me haces querer levantarme cada mañana",
        "Por cómo me miras cuando me río",
        "Porque eres mi felicidad hecha persona",
        "Por la magia que creas a nuestro alrededor",
        "Porque me haces agradecer estar viva",
        "Por tu dedicación a hacerme feliz",
        "Porque contigo cada momento es un tesoro",
        "Por las batallas que peleamos juntos",
        "Porque me das alas para volar",
        "Por tu forma de decir las cosas",
        "Porque me enseñaste que el amor todo lo puede",
        "Por cada mirada cómplice",
        "Porque me haces creer en la magia",
        "Por tu alma noble y sincera",
        "Porque me das el amor que siempre soñé",
        "Por cada atardecer que pintamos juntos",
        "Porque me llenas de luz",
        "Por tu capacidad de hacer todo divertido",
        "Porque me haces sentir que soy tu prioridad",
        "Por cada noche estrellada juntos",
        "Porque eres todo lo que siempre pedí",
        "Por cómo te preocupas por mi bienestar",
        "Porque me das seguridad emocional",
        "Por las palabras dulces antes de dormir",
        "Porque me haces querer recorrer el mundo contigo",
        "Por tu presencia que me llena de paz",
        "Porque me haces creer en nosotros",
        "Por cada sonrisa que me arrancas",
        "Porque me das fuerza para seguir",
        "Por tu forma de hacerme sentir importante",
        "Porque eres la persona con la que quiero envejecer",
        "Por cada momento de complicidad",
        "Porque me haces sentir que brillo",
        "Por tu amor incondicional",
        "Porque simplemente eres tú, Paul",
        // 201–300
        "Por cómo me proteges del frío con tu abrazo",
        "Porque eres mi estrella más brillante",
        "Por las risas que no podemos parar",
        "Porque me comprendes como nadie más",
        "Por tu mirada llena de amor",
        "Porque me haces querer escribir poesía",
        "Por cómo cantas cuando estás feliz",
        "Porque llevas alegría a donde vas",
        "Por tu forma de tomar café conmigo",
        "Porque haces que mis miedos desaparezcan",
        "Por las mañanas perezosas en cama",
        "Porque me das motivos para creer en el destino",
        "Por tu risa cuando te hago cosquillas",
        "Porque me amas en mis días buenos y malos",
        "Por cada plan descabellado que inventamos",
        "Porque me haces sentir que el mundo es nuestro",
        "Por tu forma de mirar las estrellas",
        "Porque compartimos los mismos sueños",
        "Por cómo iluminas cada habitación",
        "Porque eres mi cable a tierra",
        "Por tu capacidad de hacerme olvidar lo malo",
        "Porque me das la mano cuando tropiezo",
        "Por cada helado que compartimos",
        "Porque me haces sentir querida sin esfuerzo",
        "Por tu forma de dormir junto a mí",
        "Porque me enseñaste la paciencia del amor",
        "Por las peleas tontas que terminan en besos",
        "Porque eres mi motivo para ser feliz",
        "Por cómo susurras te amo en mi oído",
        "Porque me haces creer que los finales felices existen",
        "Por tu energía positiva",
        "Porque me haces sentir que puedo conquistar el mundo",
        "Por cada momento de vulnerabilidad compartida",
        "Porque eres mi confidente más leal",
        "Por tu forma de celebrar la vida",
        "Porque me haces sentir amada cada segundo",
        "Por cada día que eliges amarme",
        "Porque me das paz mental",
        "Por tu forma de ver lo mejor en mí",
        "Porque eres mi refugio favorito",
        "Por cómo manejas los momentos difíciles",
        "Porque me enseñaste que amar es dar sin esperar",
        "Por tu forma de sorprenderme con detalles",
        "Porque eres mi compañero de madrugadas",
        "Por cada sueño que construimos juntos",
        "Porque me haces sentir que pertenezco",
        "Por tu capacidad de transformar lo cotidiano en especial",
        "Porque me amas con todo tu ser",
        "Por las escapadas espontáneas",
        "Porque eres mi definición de felicidad",
        "Por cómo cuidas nuestro amor",
        "Porque me das razones para seguir creyendo",
        "Por tu forma de reír con los ojos",
        "Porque me haces sentir libre siendo yo misma",
        "Por cada momento que compartimos en silencio",
        "Porque eres mi compás en la vida",
        "Por tu forma de hacerme sentir bonita sin maquillaje",
        "Porque me das la valentía de enfrentar mis miedos",
        "Por cada película que vemos abrazados",
        "Porque eres mi persona, mi mundo, mi todo",
        "Por cómo me tomas de la cintura",
        "Porque me enseñaste lo que significa compromiso",
        "Por tu bondad innata",
        "Porque me haces sentir que todo tiene sentido",
        "Por las cenas improvisadas juntos",
        "Porque eres mi mayor bendición",
        "Por tu forma de caminar por la vida",
        "Porque me haces sentir que soy suficiente",
        "Por cada vez que secas mis lágrimas",
        "Porque eres mi historia de amor favorita",
        "Por tu mirada que me derrite",
        "Porque me das motivos para ser agradecida",
        "Por las locuras de media noche",
        "Porque eres mi presente y mi futuro",
        "Por cómo me inspiras a crecer",
        "Porque me haces sentir que el amor verdadero existe",
        "Por tu espíritu inquebrantable",
        "Porque me amas cuando ni yo me amo",
        "Por cada nuevo recuerdo que creamos",
        "Porque eres mi ancla y mis alas al mismo tiempo",
        "Por tu forma de abrazarme fuerte cuando me necesitas",
        "Porque me haces sentir que soy tu hogar también",
        "Por cada risa compartida en la oscuridad",
        "Porque eres la razón de mis mejores recuerdos",
        "Por tu capacidad de hacerme sentir la más importante",
        "Porque me das un amor que no sabía que existía",
        "Por cómo me miras cuando canto mal",
        "Porque eres mi persona favorita de todos los tiempos",
        "Por cada momento que pasamos juntos sin darnos cuenta",
        "Porque me haces creer que lo nuestro es para siempre",
        "Por tu forma de hacerme sentir que el mundo es pequeño junto a ti",
        "Porque me das la fuerza para ser quien quiero ser",
        "Por cada beso robado en público",
        "Porque eres mi sueño hecho realidad",
        "Por tu forma única de amarme",
        "Porque me haces sentir que merezco todo lo bueno",
        "Por cada suspiro que me sacas",
        "Porque eres mi poeta sin palabras",
        "Por tu alma que brilla más que el sol",
        "Porque me amas desde lo más profundo de tu corazón",
        // 301–400
        "Por los domingos perezosos a tu lado",
        "Porque me enseñaste que la felicidad está en los detalles",
        "Por tu forma de jugar con mi pelo",
        "Porque me haces sentir como en una película romántica",
        "Por cada mirada que dice más que mil palabras",
        "Porque eres mi cómplice favorito",
        "Por tu risa que es mi canción preferida",
        "Porque me das la paz que el mundo no puede",
        "Por cómo me abrazas cuando tengo miedo",
        "Porque me haces sentir la mujer más amada del planeta",
        "Por tu forma de pedir un deseo mirándome",
        "Porque me das alas sin atarme",
        "Por cada postal mental que guardo de nosotros",
        "Porque eres mi superpoder secreto",
        "Por tu forma de hacerme sentir que brillo",
        "Porque me amas con mis manías",
        "Por cada café que me preparas por la mañana",
        "Porque me enseñaste que el amor no tiene condiciones",
        "Por tu capacidad de hacerme sentir segura",
        "Porque me haces sentir que puedo ser vulnerable",
        "Por las canciones que son nuestras",
        "Porque eres mi lugar favorito en el mundo",
        "Por tu forma de tomar decisiones juntos",
        "Porque me das estabilidad emocional",
        "Por cada foto que nos tomamos haciendo caras",
        "Porque me haces sentir que no estoy sola nunca",
        "Por tu forma de abrir la puerta para mí",
        "Porque me das la mano para subir cada escalón",
        "Por cada ramo de flores inesperado",
        "Porque eres mi razón para despertarme con una sonrisa",
        "Por cómo me defiendes ante el mundo",
        "Porque me haces sentir que soy la indicada",
        "Por tu forma de bailar como si nadie nos viera",
        "Porque me das los mejores recuerdos",
        "Por cada te amo escrito en la ventana empañada",
        "Porque eres mi poesía favorita",
        "Por tu capacidad de transformar un mal día en uno bueno",
        "Porque me haces sentir que mi amor es correspondido",
        "Por cada viaje soñado a tu lado",
        "Porque eres mi universo completo",
        "Por tu paciencia cuando estoy de mal humor",
        "Porque me haces sentir que todo va a salir bien",
        "Por las madrugadas en las que hablamos de todo",
        "Porque me haces creer en los milagros",
        "Por tu forma de tomarme fotos cuando no me doy cuenta",
        "Porque me haces sentir artista de mi propia vida",
        "Por cada secreto que guardamos juntos",
        "Porque eres mi compañero de locuras",
        "Por tu forma de decirme que soy hermosa",
        "Porque me haces sentir que el tiempo a tu lado no es suficiente",
        "Por cada beso bajo la lluvia",
        "Porque eres mi mejor decisión",
        "Por tu forma de cuidar de los nuestros",
        "Porque me haces sentir que soy parte de algo grande",
        "Por cada abrazo de oso que me das",
        "Porque eres mi destino",
        "Por tu sonrisa cuando me ves después de un largo día",
        "Porque me haces sentir mariposas en el estómago",
        "Por las noches de pizza y películas",
        "Porque eres el mejor regalo que la vida me dio",
        "Por tu forma de pelear por nosotros",
        "Porque me haces sentir que soy tu tesoro",
        "Por cada mañana que me despiertas con un beso",
        "Porque eres mi alma gemela",
        "Por tu forma de planear nuestro futuro",
        "Porque me das la confianza de que todo estará bien",
        "Por cada momento que me haces reír hasta llorar",
        "Porque eres mi fortaleza",
        "Por tu forma de decir mi nombre",
        "Porque me haces sentir que nuestro amor es eterno",
        "Por cada paseo sin rumbo de la mano",
        "Porque eres mi primera y última opción",
        "Por tu calor cuando hace frío",
        "Porque me haces sentir la protagonista de nuestra historia",
        "Por cada carta de amor que me escribes en el corazón",
        "Porque eres mi todo, mi siempre, mi para siempre",
        "Por tu forma de hacerme sentir que vale la pena",
        "Porque me das razones infinitas para amarte",
        "Por cada amanecer compartido",
        "Porque eres mi persona en un millón",
        "Por tu forma de contar historias",
        "Porque me haces sentir que merezco ser feliz",
        "Por cada risa que curamos heridas juntos",
        "Porque eres mi brújula del corazón",
        "Por tu forma de quererme más cada día",
        "Porque me enseñaste a confiar en el amor",
        "Por cada momento de pura felicidad a tu lado",
        "Porque eres mi vitamina diaria",
        "Por tu luz que me guía en la oscuridad",
        "Porque me haces sentir invencible a tu lado",
        "Por cada noche que veo estrellas en tus ojos",
        "Porque eres mi mejor capítulo",
        "Por tu forma de hacerme sentir que pertenezco a tu mundo",
        "Porque me das la certeza de que el amor es real",
        "Por cada suspiro que compartes conmigo",
        "Porque eres mi refugio en las tormentas de la vida",
        "Por tu sonrisa tímida que me enamora",
        "Porque me amas sin límites ni condiciones",
        "Por cada paso que damos juntos hacia el futuro",
        "Porque eres mi perfecta imperfección",
        // 401–500
        "Porque me haces sentir que cada día es una celebración",
        "Por tu forma de preparar cenas especiales para mí",
        "Porque me haces sentir que soy parte de tu mundo",
        "Por cómo te brillan los ojos cuando me ves",
        "Porque me amas desde el primer día como si fuera el último",
        "Por cada dibujo que haces en mi piel con tus dedos",
        "Porque eres mi paz en medio del caos",
        "Por tu forma de decir que todo estará bien",
        "Porque me haces sentir como una princesa",
        "Por cada aventura espontánea juntos",
        "Porque eres mi GPS emocional",
        "Por tu capacidad de hacerme sentir en casa donde sea",
        "Porque me haces creer que somos invencibles juntos",
        "Por cada carrera de almohadas que hacemos",
        "Porque eres mi razón de existir más plenamente",
        "Por tu forma de compartir tu comida conmigo",
        "Porque me haces sentir que la vida es bella",
        "Por cada promesa de amor eterno",
        "Porque eres mi compañero perfecto de viaje",
        "Por tu forma de hacerme reír cuando quiero llorar",
        "Porque me enseñaste que el amor se demuestra",
        "Por cada fin de semana que pasamos juntos",
        "Porque eres mi mayor motivación",
        "Por tu forma de guardar nuestros recuerdos",
        "Porque me haces sentir que soy la elegida",
        "Por cada momento en que me siento perdida y tú me encuentras",
        "Porque eres mi rayo de sol",
        "Por tu forma de hacerme sentir que valgo la pena",
        "Porque me das una razón más para vivir cada día",
        "Por cada noche que me arropo en tus brazos",
        "Porque eres mi historia favorita para contar",
        "Por tu forma de luchar por nosotros",
        "Porque me haces sentir que somos un equipo",
        "Por cada receta que intentamos juntos",
        "Porque eres mi definición de hogar",
        "Por tu forma de mirarme que me hace temblar",
        "Porque me haces sentir que el amor no tiene fin",
        "Por cada selfie juntos que atesoro",
        "Porque eres mi complemento perfecto",
        "Por tu forma de hacerme sentir que brillo en la oscuridad",
        "Porque me das ganas de ser mejor cada día",
        "Por cada susurro de amor en mi oído",
        "Porque eres mi constante en un mundo cambiante",
        "Por tu forma de hacerme sentir que el mundo gira para nosotros",
        "Porque me amas con tus acciones, no solo con palabras",
        "Por cada atardecer que miramos juntos desde la ventana",
        "Porque eres mi ancla emocional",
        "Por tu forma de entender mis silencios",
        "Porque me haces sentir que no hay nadie más en el mundo",
        "Por cada abrazo de buenos días",
        "Porque eres mi mejor descubrimiento",
        "Por tu forma de consentirme",
        "Porque me haces sentir que soy tu prioridad número uno",
        "Por cada noche de estrellas y promesas",
        "Porque eres mi superhéroe sin capa",
        "Por tu forma de hacerme sentir que todo es posible",
        "Porque me enseñaste lo que es amar de verdad",
        "Por cada momento compartido que se vuelve eterno",
        "Porque eres mi destino escrito en las estrellas",
        "Por tu forma de mirar al futuro con esperanza",
        "Porque me haces sentir que el amor lo puede todo",
        "Por cada risa que cura mis heridas",
        "Porque eres mi medicina favorita",
        "Por tu forma de hacerme sentir que lo nuestro es especial",
        "Porque me das la certeza de que el amor es eterno",
        "Por cada momento de paz a tu lado",
        "Porque eres mi sol, mi luna y mis estrellas",
        "Por tu forma de hacerme sentir como en una canción de amor",
        "Porque me amas con cada fibra de tu ser",
        "Por cada sueño que compartimos dormidos y despiertos",
        "Porque eres mi razón para creer en el amor",
        "Por tu forma de hacerme sentir que soy la más bonita del mundo",
        "Porque me das un amor que supera toda lógica",
        "Por cada momento de conexión profunda",
        "Porque eres mi todo en una persona",
        "Por tu forma de hacerme sentir que el cielo está cerca",
        "Porque me amas desde lo más profundo",
        "Por cada vez que me haces sentir que el mundo es mejor contigo",
        "Porque eres mi corazón latiendo fuera de mi pecho",
        "Por tu forma de hacerme sentir que la distancia no existe",
        "Porque me das el mejor regalo: tu amor",
        "Por cada instante que mi corazón late por ti",
        "Porque eres mi sueño que no quiero que termine",
        "Por tu forma de hacer que cada día sea el mejor",
        "Porque me haces sentir que nuestro amor es un cuento de hadas",
        "Por cada momento que me haces sentir agradecida",
        "Porque eres mi tesoro más valioso",
        "Por tu forma de amar sin reservas",
        "Porque me haces sentir completa",
        "Por cada promesa cumplida y por cumplir",
        "Porque eres mi para siempre",
        "Por tu forma de hacerme sentir que no hay nadie como tú",
        "Porque me amas con una intensidad que me quita el aliento",
        "Por cada beso en la mejilla que me sorprende",
        "Porque eres mi arcoíris después de la tormenta",
        "Por tu forma de hacerme sentir que lo nuestro es para toda la vida",
        "Porque me das la razón más hermosa para vivir",
        "Por cada momento que eliges quedarte",
        "Porque eres mi amor infinito",
        "Por tu forma de hacerme sentir que soy el centro de tu universo",
        "Porque me amas como nadie más podría",
        // 501–600
        "Por las mañanas que huelen a ti",
        "Porque me diste el coraje de amarte",
        "Por tu forma de caminar bajo la lluvia conmigo",
        "Porque me haces sentir que la vida vale la pena",
        "Por cada sonrisa cómplice en público",
        "Porque eres mi regalo favorito de la vida",
        "Por tu forma de abrazarme en sueños",
        "Porque me haces sentir que los ángeles existen",
        "Por cada momento de ternura inesperada",
        "Porque eres mi Norte cuando me pierdo",
        "Por tu forma de hacer que lo imposible parezca fácil",
        "Porque me amas cuando menos lo merezco",
        "Por cada beso de reconciliación",
        "Porque eres la paz que busqué toda mi vida",
        "Por tu forma de convertir mis lágrimas en sonrisas",
        "Porque me haces sentir que el universo conspiró para unirnos",
        "Por cada mañana que amanezco agradecida de tenerte",
        "Porque eres mi brisa fresca en días calurosos",
        "Por tu forma de hacerme sentir que soy importante",
        "Porque me das la fuerza para enfrentar cada día",
        "Por cada momento de gratitud por tu existencia",
        "Porque eres mi más bonita casualidad",
        "Por tu forma de cuidar lo nuestro como un jardín",
        "Porque me haces sentir que cada instante cuenta",
        "Por cada beso de mariposa en mi nariz",
        "Porque eres mi razón de ser más feliz",
        "Por tu forma de llenarme de esperanza",
        "Porque me das un amor que crece cada día",
        "Por cada sueño donde apareces",
        "Porque eres mi definición de perfección",
        "Por tu forma de hacerme sentir que no hay límites",
        "Porque me amas con tu alma entera",
        "Por cada momento de complicidad en la distancia",
        "Porque eres mi vitamina de felicidad",
        "Por tu forma de hacerme sentir que somos uno",
        "Porque me das la certeza de que estamos hechos el uno para el otro",
        "Por cada instante que mi alma te reconoce",
        "Porque eres mi mayor tesoro",
        "Por tu forma de hacerme sentir que el amor es un viaje",
        "Porque me amas sin condiciones ni restricciones",
        "Por cada vez que me sorprendes con tu dulzura",
        "Porque eres mi lugar seguro en un mundo incierto",
        "Por tu forma de hacerme sentir que todo es posible si estamos juntos",
        "Porque me das alas para soñar en grande",
        "Por cada noche que dormir es mejor porque estás tú",
        "Porque eres mi compañero de todas las estaciones",
        "Por tu forma de hacerme sentir que soy tu mundo",
        "Porque me amas con paciencia y ternura",
        "Por cada momento que te elijo y me eliges",
        "Porque eres mi historia de amor eterna",
        "Por tu forma de llenar mi vida de color",
        "Porque me haces sentir que el amor es la respuesta a todo",
        "Por cada latido de mi corazón que dice tu nombre",
        "Porque eres mi razón para sonreír en los días difíciles",
        "Por tu forma de hacerme sentir que soy la dueña de tu corazón",
        "Porque me das el amor más puro y verdadero",
        "Por cada momento que me haces sentir la más especial",
        "Porque eres mi destino, mi camino y mi meta",
        "Por tu forma de hacer que los problemas parezcan pequeños",
        "Porque me amas más allá de lo imaginable",
        "Por cada segundo que paso a tu lado y deseo que sea eterno",
        "Porque eres mi persona imprescindible",
        "Por tu forma de hacerme sentir que la felicidad existe",
        "Porque me das un amor que trasciende el tiempo",
        "Por cada promesa susurrada bajo las estrellas",
        "Porque eres mi mejor versión del amor",
        "Por tu forma de hacerme sentir que cada día es San Valentín",
        "Porque me amas con la pureza de un primer amor",
        "Por cada momento de paz absoluta en tus brazos",
        "Porque eres mi más bello amanecer",
        "Por tu forma de hacerme sentir que nunca estaré sola",
        "Porque me das la razón más bella para existir",
        "Por cada risa contagiosa que compartimos",
        "Porque eres mi compañero del alma",
        "Por tu forma de hacerme sentir que el amor es una aventura",
        "Porque me amas con la fuerza de mil corazones",
        "Por cada momento que atesoro en mi memoria",
        "Porque eres mi más grande amor",
        "Por tu forma de hacerme sentir que somos la pareja perfecta",
        "Porque me das un amor que me hace creer en los sueños",
        "Por cada instante que mi vida se llena de luz por ti",
        "Porque eres mi corazón partido en dos mitades que se buscan",
        "Por tu forma de hacerme sentir que el amor es la fuerza más poderosa",
        "Porque me amas de una forma que me hace querer amarte para siempre",
        "Por cada momento que siento que somos infinitos",
        "Porque eres mi razón, mi motivo y mi inspiración",
        "Por tu forma de hacerme sentir que el cielo nos sonríe",
        "Porque me das un amor que el tiempo no puede borrar",
        "Por cada beso que sabe a eternidad",
        "Porque eres mi universo en una sola persona",
        "Por tu forma de hacerme sentir que lo nuestro es sagrado",
        "Porque me amas más de lo que las palabras pueden expresar",
        "Por cada momento compartido que vale más que todo el oro",
        "Porque eres mi más hermoso destino",
        "Por tu forma de demostrarme que el amor verdadero existe",
        "Porque me haces sentir que cada respiro es por y para ti",
        "Por cada abrazo que me hace olvidar el mundo entero",
        "Porque eres mi mejor motivo para ser feliz hoy y siempre",
        "Por tu forma de hacer latir mi corazón como loco",
        "Porque me amas de la forma más bonita posible",
        // 601–700
        "Porque tu abrazo cura cualquier tristeza",
        "Por la forma en que muerdes tu labio cuando piensas",
        "Porque me mandas memes que solo nosotros entendemos",
        "Por cómo te acuerdas de los pequeños detalles",
        "Porque eres la primera persona que quiero llamar con buenas noticias",
        "Por tu capacidad de hacer que cualquier lugar sea hogar",
        "Porque me miras y el mundo desaparece",
        "Por cada vez que me haces sentir como cuando empezamos",
        "Porque tu amor es mi superpoder",
        "Por la forma en que te emocionas por las cosas pequeñas",
        "Porque siempre tienes las palabras exactas que necesito",
        "Por cómo haces que cada estación sea especial",
        "Porque me haces sentir que merezco el mundo y más",
        "Por tu forma de preparar el mejor chocolate caliente",
        "Porque me enseñaste que el amor no es perfecto, es real",
        "Por cada noche que no pudimos dejar de hablar",
        "Porque eres mi favorito del universo entero",
        "Por la forma en que me haces sentir mariposas y paz al mismo tiempo",
        "Porque tu risa es la melodía de mi corazón",
        "Por cada vez que me dices 'todo va a estar bien' y lo creo",
        "Porque me conoces mejor que yo misma",
        "Por las listas de canciones que haces pensando en mí",
        "Porque eres mi sol en los días más oscuros",
        "Por tu manera de hacerme sentir hermosa sin intentarlo",
        "Porque nunca me sueltas la mano cuando más lo necesito",
        "Por cada aventura que aún nos falta por vivir",
        "Porque me haces querer ser la mejor versión de mí",
        "Por tu forma de hacerme sentir que el tiempo se detiene con nosotros",
        "Porque eres mi razón de vivir la vida al máximo",
        "Por cada comida compartida que se convierte en una fiesta",
        "Porque me haces sentir que nuestro amor es invencible",
        "Por la forma en que respiras cuando duermes junto a mí",
        "Porque eres mi sueño más bonito hecho realidad",
        "Por cada momento de felicidad pura e inesperada",
        "Porque me amas con un amor que me hace volar",
        "Por tu manera de hacerme sentir que soy tu todo",
        "Porque eres el dueño de cada una de mis sonrisas",
        "Por cada promesa de amor que guardas en tu corazón",
        "Porque me haces sentir que soy la persona más afortunada",
        "Por tu forma de soñar en grande junto a mí",
        "Porque eres mi compañero de ruta perfecto",
        "Por cada mirada que me roba el aliento",
        "Porque me amas con la misma intensidad del primer día",
        "Por tu capacidad de convertir cualquier momento en mágico",
        "Porque eres mi más bella locura",
        "Por cada segundo que eliges amarme una vez más",
        "Porque me haces sentir que nuestro amor puede mover montañas",
        "Por tu forma de hacerme sentir que la vida tiene sentido",
        "Porque eres mi corazón fuera de mi pecho",
        "Por cada abrazo interminable que no quiero que termine",
        "Porque me das la certeza de que elegimos bien",
        "Por tu forma de llenarme el alma de alegría",
        "Porque me amas con un amor que no tiene fecha de caducidad",
        "Por cada instante que me haces agradecer al universo por ti",
        "Porque eres mi razón de creer que el amor todo lo vence",
        "Por tu forma de hacerme sentir que somos la mejor pareja del mundo",
        "Porque me das un amor que es mi mayor orgullo",
        "Por cada atardecer que pinta nuestro amor de colores",
        "Porque eres mi destino favorito",
        "Por tu forma de hacerme sentir que cada día es una nueva oportunidad de amarte más",
        "Porque me amas con un amor que me llena por completo",
        "Por cada beso que me recuerda por qué te elegí",
        "Porque eres mi más grande aventura",
        "Por tu forma de hacer que mi corazón lata más fuerte",
        "Porque me haces sentir que nuestro amor es el más bonito del mundo",
        "Por cada noche que paso soñando contigo",
        "Porque eres mi razón para despertar con una sonrisa cada mañana",
        "Por tu forma de hacerme sentir que somos eternos",
        "Porque me amas con un amor que me hace temblar de felicidad",
        "Por cada momento que me das la certeza de que somos para siempre",
        "Porque eres mi todo, mi siempre y mi más allá",
        "Por tu forma de hacerme sentir que no hay nada que no podamos superar",
        "Porque me das un amor que es mi razón de vivir",
        "Por cada segundo compartido que se convierte en eternidad",
        "Porque eres mi mayor certeza en un mundo de dudas",
        "Por tu forma de hacerme sentir que el amor es la respuesta",
        "Porque me amas con todo lo que tienes y todo lo que eres",
        "Por cada momento que me haces agradecer estar viva",
        "Porque eres mi más hermosa razón para seguir adelante",
        "Por tu forma de hacerme sentir que nuestro amor no tiene límites",
        "Porque me das un amor que me hace crecer cada día",
        "Por cada instante de felicidad a tu lado",
        "Porque eres mi amor eterno, mi todo y mi siempre",
        "Por tu forma de hacer que lo cotidiano sea extraordinario",
        "Porque me amas de la forma más pura que existe",
        "Por cada sonrisa tuya que me llena de vida",
        "Porque eres la persona con la que quiero vivir todas mis vidas",
        "Por tu forma de hacer que mi alma cante de alegría",
        "Porque me das un amor que brilla más que cualquier estrella",
        "Por cada momento que me demuestras que el amor verdadero no se rinde",
        "Porque eres mi mundo entero en una sola persona",
        "Por tu forma de hacerme sentir la persona más querida del planeta",
        "Porque me amas con una devoción que me conmueve",
        "Por cada instante que nuestro amor crece más fuerte",
        "Porque eres mi razón de ser más feliz de lo que jamás imaginé",
        "Por tu forma de hacerme sentir que el amor es nuestra mayor fortaleza",
        "Porque me das un amor que llena todos los vacíos",
        "Por cada momento que me haces agradecer al cielo por tu existencia",
        "Porque eres mi más grande bendición y mi mayor tesoro",
        "Por tu forma de hacerme sentir que todo lo que vivimos juntos vale oro",
        // 701–800
        "Por las notas de amor que me dejas en lugares inesperados",
        "Porque me tomas en cuenta para cada decisión importante",
        "Por la forma en que me cuidas cuando nadie más lo hace",
        "Porque me das la libertad de ser yo misma sin juicios",
        "Por cada abrazo que me das como si fuera el último",
        "Porque conoces mis sueños mejor que nadie",
        "Por tu mirada que me llena de calidez",
        "Porque siempre sabes cuándo necesito un abrazo",
        "Por cada momento de vulnerabilidad que compartes conmigo",
        "Porque me amas incluso cuando estoy difícil de amar",
        "Por tu forma de iluminar los días más grises",
        "Porque me das la estabilidad que necesito para crecer",
        "Por cada vez que me dices que estás orgulloso de mí",
        "Porque confías en mí con los ojos cerrados",
        "Por tu manera de celebrar nuestro amor cada día",
        "Porque me haces sentir que los problemas son temporales pero nosotros somos eternos",
        "Por cada cena a la luz de las velas improvisada",
        "Porque eres mi compañero de sueños imposibles",
        "Por tu forma de hacerme sentir que cada día es una nueva aventura",
        "Porque me das el coraje de perseguir mis metas",
        "Por cada carta de amor que guardas en tu corazón para mí",
        "Porque eres la persona que siempre quise encontrar",
        "Por tu capacidad de convertir lo ordinario en algo extraordinario",
        "Porque me amas con la intensidad que el mundo necesita",
        "Por cada momento de silencio que se llena con tu amor",
        "Porque eres mi paz interior hecha persona",
        "Por tu forma de tomarte la vida con alegría y optimismo",
        "Porque me haces creer que el amor puede curar cualquier herida",
        "Por cada risa que compartimos y que se convierte en medicina",
        "Porque eres mi refugio emocional más seguro",
        "Por tu forma de soñar conmigo despiertos",
        "Porque me das un amor que no le teme al tiempo",
        "Por cada instante que nuestras almas se conectan sin palabras",
        "Porque eres mi mayor felicidad y mi mayor calma",
        "Por tu forma de hacerme sentir que soy suficiente tal como soy",
        "Porque me amas con un amor que no pide nada a cambio",
        "Por cada momento que me haces creer que los cuentos de amor existen",
        "Porque eres mi poeta, mi músico y mi artista del amor",
        "Por tu forma de hacer que cada reunión sea una fiesta",
        "Porque me das la certeza de que juntos podemos con todo",
        "Por cada noche estrellada que me dedicas",
        "Porque eres el amor que trasciende todo lo conocido",
        "Por tu forma de hacerme sentir que la vida es un regalo",
        "Porque me amas con todo tu universo interior",
        "Por cada momento que me das la fuerza de seguir soñando",
        "Porque eres mi razón más profunda para agradecer",
        "Por tu forma de llenar cada espacio vacío con amor",
        "Porque me das un amor que me inspira cada amanecer",
        "Por cada instante que eliges amarme sobre todas las cosas",
        "Porque eres mi camino, mi verdad y mi vida",
        "Por tu forma de hacerme sentir que nada ni nadie puede separarnos",
        "Porque me amas con una fuerza que mueve el mundo",
        "Por cada momento de éxtasis compartido",
        "Porque eres mi sonrisa perpetua",
        "Por tu forma de amar que me hace creer en lo imposible",
        "Porque me das un amor que supera cualquier expectativa",
        "Por cada instante que me demuestras que eres para mí",
        "Porque eres mi más lindo amanecer después de la noche más oscura",
        "Por tu forma de hacerme sentir que nuestro amor es indestructible",
        "Porque me amas con la certeza de quien ha encontrado su mitad",
        "Por cada momento de plenitud absoluta a tu lado",
        "Porque eres mi razón de ser, mi todo y mi eternidad",
        "Por tu forma de hacer que cada respiro sea más dulce",
        "Porque me das un amor que me hace agradecer cada latido",
        "Por cada instante que siento que nuestro amor toca el cielo",
        "Porque eres mi luz al final del túnel y el sol de mi mañana",
        "Por tu forma de hacerme sentir que la eternidad existe",
        "Porque me amas más de lo que jamás creí posible",
        "Por cada momento que me das la fuerza de amar sin miedo",
        "Porque eres mi todo en este mundo y en cualquier otro",
        "Por tu forma de hacerme sentir que nuestro amor es el milagro más grande",
        "Porque me das un amor que me hace creer que los ángeles existen",
        "Por cada instante de amor puro que compartimos",
        "Porque eres mi más bella razón para existir",
        "Por tu forma de hacerme sentir que somos la historia de amor más bonita",
        "Porque me amas con un amor que es mi mayor regalo",
        "Por cada momento que me haces sentir que soy la persona más amada",
        "Porque eres mi eternidad hecha realidad",
        "Por tu forma de hacerme creer en el poder del amor",
        "Porque me das un amor que me completa y me transforma",
        "Por cada instante que me demuestras que el amor lo puede todo",
        "Porque eres mi razón más hermosa para seguir creyendo en el amor",
        "Por tu forma de hacerme sentir que somos invencibles cuando estamos juntos",
        "Porque me amas con cada célula de tu ser",
        "Por cada momento compartido que atesoro como un diamante",
        "Porque eres mi más grande historia de amor",
        "Por tu forma de hacerme sentir que el cielo es nuestro techo",
        "Porque me das un amor que ilumina mi camino",
        "Por cada instante que me haces sentir la más querida del universo",
        "Porque eres mi destino elegido por las estrellas",
        "Por tu forma de hacerme sentir que nuestro amor no tiene fronteras",
        "Porque me amas con la ternura de quien ha encontrado su tesoro",
        "Por cada momento que me haces sentir que soy tu razón de vivir",
        "Porque eres mi poema de amor eterno",
        "Por tu forma de hacerme sentir que la felicidad tiene tu nombre",
        "Porque me das un amor que es mi mayor fortaleza y mi más dulce debilidad",
        "Por cada instante que nuestro amor se hace más fuerte e indestructible",
        "Porque eres mi sol, mi luna, mis estrellas y todo el universo",
        "Por tu forma de hacerme sentir que somos el amor más grande jamás contado",
        "Porque me amas de una manera que trasciende el tiempo y el espacio",
        // 801–900
        "Porque contigo aprendí que el amor no es solo un sentimiento, es una elección diaria",
        "Por cómo me haces querer ser mejor persona cada mañana",
        "Porque tu presencia es el mejor regalo que puedo recibir",
        "Por las peleas tontas que terminan en risas y abrazos",
        "Porque me miras y siento que el tiempo se congela",
        "Por tu capacidad de hacer especial cualquier momento ordinario",
        "Porque me das la tranquilidad de saber que siempre estarás ahí",
        "Por cada vez que cantas en la ducha y me haces sonreír",
        "Porque me enseñaste que la imperfección es perfecta cuando hay amor",
        "Por las conversaciones profundas a las tres de la madrugada",
        "Porque tu amor me hace sentir invulnerable",
        "Por cada paseo bajo las estrellas tomados de la mano",
        "Porque me haces querer escribir mil poemas para ti",
        "Por la forma en que te preocupas por mi felicidad",
        "Porque eres la persona que quiero ver cada mañana al despertar",
        "Por cada momento en que tu amor me salva de mí misma",
        "Porque con una sola mirada tuya olvido todos mis problemas",
        "Por la forma en que entrelazas tus dedos con los míos",
        "Porque me haces sentir que juntos podemos contra el mundo entero",
        "Por cada amanecer que se vuelve más bonito porque estás a mi lado",
        "Porque tu amor es como una estrella que nunca deja de brillar",
        "Por las tardes de café y conversaciones sin fin",
        "Porque me das la seguridad de que nuestro amor es inquebrantable",
        "Por tu forma de hacerme sentir que soy la persona más especial del mundo",
        "Porque me enseñaste que el amor verdadero no necesita ser perfecto",
        "Por cada vez que me sorprendes con un gesto de cariño inesperado",
        "Porque eres la razón por la que creo en los finales felices",
        "Por la forma en que me haces sentir que cada día es un nuevo comienzo",
        "Porque tu amor me da la fuerza para enfrentar cualquier desafío",
        "Por cada momento en que tu sonrisa ilumina mi mundo entero",
        "Porque me haces sentir que la vida es una aventura maravillosa",
        "Por las veces que me haces reír hasta que me duele el estómago",
        "Porque tu amor es la melodía más bonita que he escuchado",
        "Por cada instante en que me haces sentir que soy parte de algo increíble",
        "Porque me das la certeza de que nuestro amor durará para siempre",
        "Por la forma en que me haces sentir que somos almas gemelas",
        "Porque tu amor me inspira a soñar más grande que nunca",
        "Por cada momento en que me haces sentir que soy amada sin condiciones",
        "Porque eres mi refugio, mi fuerza y mi esperanza",
        "Por tu forma de hacer que los días difíciles sean soportables",
        "Porque me amas con una pasión que me deja sin palabras",
        "Por cada instante en que me haces sentir que el mundo es nuestro",
        "Porque tu amor es el combustible que impulsa mis sueños",
        "Por la forma en que me haces sentir que cada momento juntos es sagrado",
        "Porque me das la valentía de amar sin reservas ni temores",
        "Por cada vez que tu mirada me dice más que mil discursos",
        "Porque eres la persona que le da sentido a mi existencia",
        "Por la forma en que me haces sentir que soy tu universo entero",
        "Porque tu amor me hace sentir que soy la persona más afortunada del planeta",
        "Por cada momento en que tu presencia me llena de una felicidad indescriptible",
        "Porque me amas con la intensidad de mil soles ardiendo",
        "Por la forma en que me haces sentir que nuestro amor es la fuerza más poderosa del universo",
        "Porque tu amor es mi razón para creer que todo es posible",
        "Por cada instante en que me haces sentir que somos eternos e inseparables",
        "Porque eres mi amor, mi vida y mi razón de existir",
        "Por la forma en que me haces sentir que el amor verdadero trasciende todo",
        "Porque tu amor me completa de una manera que jamás creí posible",
        "Por cada momento en que me haces sentir que nuestro amor es un milagro",
        "Porque eres mi mayor certeza en este mundo lleno de incertidumbres",
        "Por la forma en que me haces sentir que soy exactamente donde debo estar",
        "Porque tu amor es la luz que me guía en la oscuridad más profunda",
        "Por cada instante que tu amor me hace sentir que la vida es hermosa",
        "Porque me amas con una devoción que me conmueve hasta las lágrimas",
        "Por la forma en que me haces sentir que nuestro amor es invencible",
        "Porque tu amor es mi mayor tesoro y mi más grande orgullo",
        "Por cada momento en que me haces sentir que somos la definición del amor",
        "Porque eres mi sol de cada mañana y mi luna de cada noche",
        "Por la forma en que me haces sentir que el amor es la respuesta a todo",
        "Porque tu amor me hace creer que los milagros suceden cada día",
        "Por cada instante que me haces sentir que soy la persona más querida del mundo",
        "Porque eres la persona que le da color a mi vida entera",
        "Por la forma en que me haces sentir que todo tiene sentido cuando estamos juntos",
        "Porque tu amor es mi refugio seguro en cualquier tormenta",
        "Por cada momento que me demuestra que nuestro amor solo se hace más fuerte",
        "Porque eres mi compañero de cada batalla y de cada victoria",
        "Por la forma en que me haces sentir que soy tu mayor prioridad",
        "Porque tu amor me inspira a vivir cada día con pasión y gratitud",
        "Por cada instante que me recuerda por qué te elegí a ti",
        "Porque eres la persona con la que quiero compartir cada amanecer",
        "Por la forma en que me haces sentir que nuestro amor es la historia más bonita jamás contada",
        "Porque tu amor es mi mayor motivación y mi más dulce inspiración",
        "Por cada momento que me haces agradecer al universo por haberte puesto en mi camino",
        "Porque eres mi todo y con eso tengo todo lo que necesito",
        "Por la forma en que me haces sentir que el amor verdadero solo crece con el tiempo",
        "Porque tu amor me da la certeza de que juntos podemos superar cualquier obstáculo",
        "Por cada instante que me haces sentir la persona más amada de toda la historia",
        "Porque eres mi amor más grande, mi felicidad más profunda y mi paz más completa",
        "Por la forma en que me haces sentir que cada día a tu lado es el mejor día de mi vida",
        "Porque tu amor es el regalo más valioso que he recibido jamás",
        "Por cada momento que me hace creer que nuestro amor puede cambiar el mundo",
        "Porque eres mi estrella más brillante en el cielo de mi vida",
        "Por la forma en que me haces sentir que somos invencibles cuando estamos juntos",
        "Porque tu amor es la fuerza que me impulsa a ser mejor cada día",
        "Por cada instante que me demuestra que nuestro amor es la cosa más hermosa del universo",
        "Porque me amas como nadie más lo ha hecho ni lo hará jamás",
        "Por la forma en que me haces sentir que nuestro amor es un poema que nunca termina",
        "Porque tu amor es mi canción favorita, la que quiero escuchar por siempre",
        "Por cada momento en que me haces sentir que soy el centro de tu universo",
        "Porque eres el amor más bonito que la vida pudo regalarme",
        "Por la forma en que me haces sentir que nuestra historia de amor es eterna",
        // 901–1000
        "Porque a tu lado descubrí lo que significa estar completa",
        "Por la forma en que tu corazón late junto al mío",
        "Porque cada día eliges amarme y eso es lo más hermoso",
        "Por los planes a largo plazo que hacemos con ilusión",
        "Porque me diste el valor de creer en nosotros dos",
        "Por la forma en que me haces sentir que soy tu hogar",
        "Porque tu risa es la banda sonora de mi felicidad",
        "Por cada vez que me miras y veo nuestro futuro en tus ojos",
        "Porque me enseñaste que amar es la decisión más valiente",
        "Por las noches donde solo necesitamos estar juntos",
        "Porque eres mi compañero de vida, de sueños y de locuras",
        "Por la forma en que tu amor me transformó para siempre",
        "Porque me haces querer vivir mil vidas solo para amarte en cada una",
        "Por cada instante que nuestro amor desafía lo imposible",
        "Porque tu presencia es la respuesta a todas mis preguntas",
        "Por la certeza de que en otra vida te volvería a elegir",
        "Porque me amas con la misma fuerza de los océanos",
        "Por cada momento en que siento que nuestro amor puede mover montañas",
        "Porque tu amor es mi ancla, mis alas y mi horizonte",
        "Por la forma en que me haces sentir que cada latido es un te amo",
        "Porque eres la prueba de que los sueños se hacen realidad",
        "Por las mil y una formas en que me demuestras tu amor cada día",
        "Porque me haces sentir que nuestro amor es más grande que el universo",
        "Por cada momento que me haces sentir que la vida es un regalo que quiero abrir contigo",
        "Porque eres mi primer amor, mi último amor y mi amor eterno",
        "Por la forma en que me haces sentir que cada momento juntos es perfecto",
        "Porque tu amor me enseñó que la felicidad no se busca, se construye",
        "Por cada instante que me recuerda que encontré en ti todo lo que necesitaba",
        "Porque eres la persona que hace que mi corazón cante de alegría",
        "Por la forma en que me haces sentir que nuestro amor es la mayor aventura de nuestras vidas",
        "Porque tu amor es como el sol: cálido, constante e imprescindible",
        "Por cada momento que me haces sentir que el cielo nos creó para estar juntos",
        "Porque me amas con un amor que es más fuerte que cualquier tormenta",
        "Por la forma en que me haces sentir que somos dos almas que se encontraron después de mucho buscar",
        "Porque tu amor me da la certeza de que juntos escribiremos la historia más bonita",
        "Por cada instante que me demuestra que nuestro amor es inmortal",
        "Porque eres mi razón, mi pasión, mi devoción y mi más grande emoción",
        "Por la forma en que me haces sentir que el amor es el idioma que hablamos sin palabras",
        "Porque tu amor me inspira poesía, música y arte en cada respirar",
        "Por cada momento que me da la certeza de que te amaré todos los días de mi vida",
        "Porque eres mi primer pensamiento, mi último suspiro y todo lo que hay en medio",
        "Por la forma en que me haces sentir que nuestro amor cambia el mundo un poquito cada día",
        "Porque tu amor es el milagro más bonito que me ha regalado la existencia",
        "Por cada instante de amor que compartimos y que se convierte en eternidad",
        "Porque eres mi persona favorita en este universo y en todos los que existan",
        "Por la forma en que me haces sentir que cada respiro es una declaración de amor",
        "Porque tu amor me enseñó que lo más bonito de la vida es compartirla contigo",
        "Por cada momento que me confirma que elegirte fue la mejor decisión de mi vida",
        "Porque eres mi alma entera, mi corazón completo y mi amor infinito",
        "Por la forma en que me haces sentir que nuestro amor es la cosa más pura y verdadera que existe",
        "Porque me amas con un amor que trasciende el tiempo, la distancia y todo lo imaginable",
        "Por cada instante que me das la certeza de que juntos somos invencibles, eternos e infinitos",
        "Porque eres el amor de mi vida, la razón de mi felicidad y el dueño absoluto de mi corazón",
        "Por cada latido, cada suspiro, cada sonrisa y cada lágrima que compartimos juntos",
        "Porque tu amor es lo más hermoso, lo más grande y lo más sagrado que existe en mi mundo",
        "Por la forma en que me haces sentir que nuestro amor es la razón por la que el universo existe",
        "Porque eres mi todo: mi amor, mi vida, mi sueño, mi realidad, mi siempre y mi para siempre",
        "Porque desde que te conocí supe que eras tú, siempre fuiste tú, y siempre serás tú",
        "Por tu mirada sincera que me desarma por completo",
        "Porque contigo he aprendido el verdadero significado de la complicidad",
        "Por la paz que siento cuando me rodeas con tus brazos",
        "Porque haces que los d"Por tu mirada sincera que me desarma por completo",
        "Porque contigo he aprendido el verdadero significado de la complicidad",
        "Por la paz que siento cuando me rodeas con tus brazos",
        "Porque haces que los momentos tristes sean muy llevaderos",
        "Por la paciencia y el gran afecto con el que me escuchas siempre",
        "Porque eres mi refugio seguro en este mundo tan inestable",
        "Por los bellos detalles que demuestran lo mucho que te importo",
        "Porque tu amor me llena de una felicidad que no se puede explicar",
        "Por la dulzura de tus besos que me hacen flotar en el aire",
        "Porque a tu lado he descubierto una gran version de mi misma",
        "Por los proyectos y metas que construimos juntos cada dia",
        "Porque compartimos risas que se quedan grabadas en el alma",
        "Por tu apoyo incondicional en cada paso que decido dar",
        "Porque tu sola presencia tiene el poder de alegrar mi dia",
        "Por la magia de nuestras conversaciones de madrugada",
        "Porque eres la persona con la que quiero compartir cada amanecer",
        "Por la nobleza de tu corazon que me inspira a ser mejor",
        "Porque contigo la vida es una aventura maravillosa que no quiero terminar",
        "Por la complicidad que existe entre nosotros con una sola mirada",
        "Por la forma en que me haces sentir amada en cada momento",
        "Por tu forma de ver el mundo que me llena de admiracion",
        "Porque cada abrazo tuyo tiene el poder de sanar cualquier dolor",
        "Por las risas compartidas por cosas divertidas que solo nosotros entendemos",
        "Porque contigo el futuro se ve brillante y lleno de esperanza",
        "Por tu ternura infinita que me conmueve en lo mas profundo",
        "Porque me inspiras a imaginar despierta todo lo que vendra",
        "Por como respetas mis espacios y apoyas mis decisiones",
        "Porque eres mi pareja ideal para recorrer el camino de la vida",
        "Por la calidez de tu mano junto a la mia al caminar",
        "Por la forma en que me demuestras que tu amor es un gran regalo",
        "Por como me animas a superar mis propios miedos",
        "Porque tu sonrisa es el faro que guia mis momentos de oscuridad",
        "Por la tranquilidad que me transmite el sonido de tu respiracion",
        "Porque contigo he aprendido a disfrutar de las cosas simples",
        "Por tu generosidad constante que no busca nada a cambio",
        "Porque haces que nuestro hogar sea el lugar mas feliz de la tierra",
        "Por la complicidad inquebrantable que nos une frente a todo",
        "Porque inspiras mis sonrisas mas sinceras y profundas",
        "Por cada palabra de aliento que me das cuando dudo de mi misma",
        "Porque te amo por todo lo que eres, lo que hemos sido y lo que seremos juntos",
        
        "Porque te amo, Paul, con las mil razones de esta lista y con un millón más que no caben en palabras",
        "Y la razón más importante de todas: porque eres tú. Simplemente tú. Te amo, Paul. 💜"
    ];

    // ── Build Reason Cards ──
    const grid = document.getElementById('razonesGrid');

    razones.forEach((razon, index) => {
        const num = index + 1;
        const card = document.createElement('div');
        card.classList.add('reason-card');

        // Milestone every 100
        if (num % 100 === 0) {
            card.classList.add('milestone');
        }

        card.innerHTML = `
            <span class="reason-number">${num}</span>
            <p class="reason-text">${razon}</p>
        `;
        grid.appendChild(card);
    });

    // ── Update counter total ──
    document.querySelector('.counter-total').textContent = razones.length;

    // ── Scroll Reveal with Intersection Observer ──
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('visible');
                observer.unobserve(entry.target);
            }
        });
    }, {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    });

    document.querySelectorAll('.reason-card').forEach(card => {
        observer.observe(card);
    });

    // ── Progress Bar & Counter ──
    const progressFill = document.getElementById('progressFill');
    const counterCurrent = document.querySelector('.counter-current');
    const cards = document.querySelectorAll('.reason-card');

    function updateProgress() {
        // Progress bar
        const scrollTop = window.scrollY;
        const docHeight = document.documentElement.scrollHeight - window.innerHeight;
        const scrollPercent = docHeight > 0 ? (scrollTop / docHeight) * 100 : 0;
        progressFill.style.width = Math.min(scrollPercent, 100) + '%';

        // Counter: count visible cards
        let visibleCount = 0;
        cards.forEach(card => {
            if (card.classList.contains('visible')) {
                visibleCount++;
            }
        });
        counterCurrent.textContent = visibleCount;
    }

    window.addEventListener('scroll', updateProgress, { passive: true });
    updateProgress();

})();
